/** @type {import('tailwindcss').Config} */

module.exports = {
    content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
    darkMode: ['class'],
    theme: {
        fontSize: {
            h1: '32px',
            h2: '24px',
            h3: '20px',
            h4: '18px',
            h5: '16px',
            h6: '14px',
            p: '14px',
            'sub-p': '13px',
            'sm-sub-p': '12px',
            'itl-note': '11px',
        },
        extend: {
            colors: {
                'itl-primary': 'var(--primary-color)',
                'primary-dark': 'var(--primary-color-dark)',
                'itl-error': 'var(--error-color)',
                'error-dark': 'var(--error-color-dark)',
                'itl-success': 'var(--success-color)',
                'success-dark': 'var(--success-color-dark)',
                'light-0': 'var(--light-0)',
                'light-50': 'var(--light-50)',
                'light-100': 'var(--light-100)',
                'light-200': 'var(--light-200)',
                'light-300': 'var(--light-300)',
                'light-400': 'var(--light-400)',
                'light-500': 'var(--light-500)',
                'light-600': 'var(--light-600)',
                'light-700': 'var(--light-700)',
                'light-740': 'var(--light-740)',
                'light-800': 'var(--light-800)',
                'light-900': 'var(--light-900)',
                'light-1000': 'var(--light-1000)',
                'light-1100': 'var(--light-1100)',
                'light-1200': 'var(--light-1200)',
                'light-1300': 'var(--light-1300)',
                'light-1400': 'var(--light-1400)',
                // dark mode colors
                'dark-0': 'var(--dark-0)',
                'dark-100': 'var(--dark-100)',
                'dark-200': 'var(--dark-200)',
                'dark-300': 'var(--dark-300)',
                'dark-400': 'var(--dark-400)',
                'dark-500': 'var(--dark-500)',
                'dark-600': 'var(--dark-600)',
                'dark-700': 'var(--dark-700)',
                'dark-800': 'var(--dark-800)',
                'dark-900': 'var(--dark-900)',
                'dark-1000': 'var(--dark-1000)',
                // unused colors
                // 'dark-50': 'var(--dark-50)',
                // 'dark-740': 'var(--dark-740)',
                // 'dark-1100': 'var(--dark-1100)',
                // 'dark-1200': 'var(--dark-1200)',
                // 'dark-1300': 'var(--dark-1300)',
                // 'dark-1400': 'var(--dark-1400)',

                'border-color': 'var(--border-color)',
                'bi-green': 'var(--bi-green)',
                'bi-yellow': 'var(--bi-yellow)',
                'bi-gray': 'var(--bi-gray)',
                'input-border-color': 'var(--input-border-color)',
                'input-text-color': 'var(--input-text-color)',
                'input-focused-border': 'var(--input-focused-border)',
            },
            boxShadow: {
                'itl-sm': '0 1px 3px 0 rgba(0, 0, 0, 0.06)',
                'itl-md': '0 4px 6px 0 rgba(0, 0, 0, 0.05), 0 10px 15px 0 rgba(0, 0, 0, 0.1)',
            },
            fontFamily: {
                interRegular: ['Inter-Regular'],
                interSemiBold: ['Inter-SemiBold', 'sans-serif'],
                interMedium: ['Inter-Medium', 'sans-serif'],
                interBold: ['Inter-Bold', 'sans-serif'],
            },
            borderRadius: {
                'itl-sm': '4px',
                'itl-md': '6px',
            },
            height: {
                'sm-btn': '28px',
                'md-btn': '32px',
                'lg-btn': '40px',
                'itl-input': '32px',
                'itl-dropdown': '32px',
                'sm-toggle': '16px',
                'md-toggle': '20px',
                'sm-checkbox': '12px',
                'md-checkbox': '16px',
                'sm-radio': '12px',
                'md-radio': '16px',
            },
            padding: {
                'sm-btn-x': '6px',
                'sm-btn-y': '12px',
                'md-btn-x': '8px',
                'md-btn-y': '12px',
                'lg-btn-x': '12px',
                'lg-btn-y': '24px',
                'itl-input-x': '9px',
                'itl-input-y': '12px',
                'itl-dropdown-x': '8px',
                'itl-dropdown-y': '12px',
            },
            fontSize: {
                'sm-btn': '12px',
                'md-btn': '12px',
                'lg-btn': '14px',
                'dropdown-label': '14px',
            },
        },
    },
    plugins: [],
};
