import { dataTableVariables, commonFilterModal } from '@/components/itl-dataTable-files/itl-dataTable/commonVariable.js';
import { ref } from 'vue'; // Importing watch from Vue 3

export const viewNdrVariables = ref(dataTableVariables.value);
viewNdrVariables.value.isEscalateModalVisible = ref(false);
viewNdrVariables.value.isAttemptHistoryModalVisible = ref(false);
export const filterModal = commonFilterModal;
export const staticTabs = [
    { name: 'Action Required', id: '1', value: 'action_required' },
    { name: 'Action Requested', id: '2', value: 'action_requested' },
    { name: 'RTO', id: '3', value: 'rto' },
    { name: 'Delivered', id: '4', value: 'delivered' },
    { name: 'Manual Reattempt', id: '7', value: 'manual_reattempt' },
    { name: 'Incorrect Address', id: '8', value: 'incorrect_address' },
    { name: 'All', id: '9', value: 'all' },
];

export const staticAttemptHistoryData = {
    modalTitle: 'Attempt History',
    awbNo: '1234567890',
    isRtoOrder: true,
    attemptHistoryCardData: [
        {
            title: '1st Attempt',
            processData: [
                {
                    img1: 'courier-logo',
                    img2: 'right-arrow',
                    img3: 'vendor-name-logo',
                    descriptionImg: '',
                    vendorName: 'Akshay Syal',
                    status: {
                        text: 'Success',
                        color: 'greenClr',
                    },
                    description: 'Items assigned for customer pickup at',
                    date: '12 July 2023',
                    time: '8:04 AM',
                    chipText: '',
                    chipType: '',
                    isPanel: false,
                },
                {
                    img1: 'courier-logo',
                    img2: 'right-arrow',
                    img3: 'vendor-name-logo',
                    descriptionImg: '',
                    vendorName: 'Akshay Syal',
                    status: '',
                    description: 'Customer Not Contactable',
                    date: '12 July 2023',
                    time: '8:04 AM',
                    chipText: '',
                    chipType: '',
                },
                {
                    img1: 'ITL-logo',
                    img2: 'right-arrow',
                    img3: 'vendor-name-logo',
                    descriptionImg: 'declined-call',
                    vendorName: 'Akshay Syal',
                    status: '',
                    description: 'Called Buyer',
                    date: '12 July 2023',
                    time: '8:04 AM',
                    chipText: 'iThinkLogistics - Auto',
                    chipType: 'auto',
                    isPanel: false,
                },
                {
                    img1: 'ITL-logo',
                    img2: 'right-arrow',
                    img3: 'vendor-name-logo',
                    descriptionImg: 'declined-call',
                    vendorName: 'Akshay Syal',
                    status: {
                        text: 'Call not received by Buyer',
                        color: 'brownClr',
                    },
                    description: 'Called Buyer',
                    date: '12 July 2023',
                    time: '8:04 AM',
                    chipText: 'iThinkLogistics - Auto',
                    chipType: 'auto',
                    isPanel: false,
                },
                {
                    img1: 'ITL-logo',
                    img2: 'right-arrow',
                    img3: 'vendor-name-logo',
                    descriptionImg: '',
                    vendorName: 'Akshay Syal',
                    status: {
                        text: 'Reattempt via Ndr Call',
                        color: 'greenClr',
                    },
                    description: 'Called Buyer',
                    date: '12 July 2023',
                    time: '8:04 AM',
                    chipText: 'iThinkLogistics - Manual',
                    chipType: 'manual',
                    isPanel: false,
                },
                {
                    img1: 'ITL-logo',
                    img2: 'right-arrow',
                    img3: 'vendor-name-logo',
                    descriptionImg: '',
                    vendorName: 'Akshay Syal',
                    status: {
                        text: '',
                        color: '',
                        bgColor: '',
                    },
                    description: 'Called Buyer',
                    date: '12 July 2023',
                    time: '8:04 AM',
                    chipText: '',
                    chipType: '',
                    isPanel: true,
                    panel: {
                        heading: 'SMS',
                        img1: 'ITL-logo',
                        content: 'Order Minoxidil 5%... from Traya Health is undelievered due to residence closed; Unable to... Confirm reason: https//itl.com/order/1234567890 Team, iThinkLogistics',
                    },
                },
                {
                    img1: 'you-name-logo',
                    img2: 'right-arrow',
                    img3: 'courier-logo',
                    descriptionImg: '',
                    vendorName: 'Delhivery',
                    status: {
                        text: '',
                        color: '',
                        bgColor: '',
                    },
                    description: 'Incorrect Updated Address:- B902 Delhi, India',
                    date: '12 July 2023',
                    time: '8:04 AM',
                    chipText: '',
                    chipType: '',
                    isPanel: false,
                },
            ],
        },
        {
            title: '2nd Attempt',
            processData: [
                {
                    img1: 'courier-logo',
                    img2: 'right-arrow',
                    img3: 'vendor-name-logo',
                    descriptionImg: '',
                    vendorName: 'Akshay Syal',
                    status: {
                        text: 'Success',
                        color: 'greenClr',
                    },
                    description: 'Items assigned for customer pickup at',
                    date: '12 July 2023',
                    time: '8:04 AM',
                    chipText: '',
                    chipType: '',
                    isPanel: false,
                },
                {
                    img1: 'courier-logo',
                    img2: 'right-arrow',
                    img3: 'vendor-name-logo',
                    descriptionImg: '',
                    vendorName: 'Akshay Syal',
                    status: '',
                    description: 'Customer Not Contactable',
                    date: '12 July 2023',
                    time: '8:04 AM',
                    chipText: '',
                    chipType: '',
                },
                {
                    img1: 'ITL-logo',
                    img2: 'right-arrow',
                    img3: 'vendor-name-logo',
                    descriptionImg: 'declined-call',
                    vendorName: 'Akshay Syal',
                    status: '',
                    description: 'Called Buyer',
                    date: '12 July 2023',
                    time: '8:04 AM',
                    chipText: 'iThinkLogistics - Auto',
                    chipType: 'auto',
                    isPanel: false,
                },
                {
                    img1: 'ITL-logo',
                    img2: 'right-arrow',
                    img3: 'vendor-name-logo',
                    descriptionImg: 'declined-call',
                    vendorName: 'Akshay Syal',
                    status: {
                        text: 'Call not received by Buyer',
                        color: 'brownClr',
                    },
                    description: 'Called Buyer',
                    date: '12 July 2023',
                    time: '8:04 AM',
                    chipText: 'iThinkLogistics - Auto',
                    chipType: 'auto',
                    isPanel: false,
                },
                {
                    img1: 'ITL-logo',
                    img2: 'right-arrow',
                    img3: 'vendor-name-logo',
                    descriptionImg: '',
                    vendorName: 'Akshay Syal',
                    status: {
                        text: 'Reattempt via Ndr Call',
                        color: 'greenClr',
                    },
                    description: 'Called Buyer',
                    date: '12 July 2023',
                    time: '8:04 AM',
                    chipText: 'iThinkLogistics - Manual',
                    chipType: 'manual',
                    isPanel: false,
                },
                {
                    img1: 'ITL-logo',
                    img2: 'right-arrow',
                    img3: 'vendor-name-logo',
                    descriptionImg: '',
                    vendorName: 'Akshay Syal',
                    status: {
                        text: '',
                        color: '',
                        bgColor: '',
                    },
                    description: 'Called Buyer',
                    date: '12 July 2023',
                    time: '8:04 AM',
                    chipText: '',
                    chipType: '',
                    isPanel: true,
                    panel: {
                        heading: 'SMS',
                        img1: 'ITL-logo',
                        content: 'Order Minoxidil 5%... from Traya Health is undelievered due to residence closed; Unable to... Confirm reason: https//itl.com/order/123456789 Team, iThinkLogistics',
                    },
                },
                {
                    img1: 'you-name-logo',
                    img2: 'right-arrow',
                    img3: 'courier-logo',
                    descriptionImg: '',
                    vendorName: 'Delhivery',
                    status: {
                        text: '',
                        color: '',
                        bgColor: '',
                    },
                    description: 'Incorrect Updated Address:- B902 Delhi, India',
                    date: '12 July 2023',
                    time: '8:04 AM',
                    chipText: '',
                    chipType: '',
                    isPanel: false,
                },
            ],
        },
        {
            title: '3rd Attempt',
            processData: [
                {
                    img1: 'courier-logo',
                    img2: 'right-arrow',
                    img3: 'vendor-name-logo',
                    descriptionImg: '',
                    vendorName: 'Akshay Syal',
                    status: {
                        text: 'Success',
                        color: 'greenClr',
                    },
                    description: 'Items assigned for customer pickup at',
                    date: '12 July 2023',
                    time: '8:04 AM',
                    chipText: '',
                    chipType: '',
                    isPanel: false,
                },
                {
                    img1: 'courier-logo',
                    img2: 'right-arrow',
                    img3: 'vendor-name-logo',
                    descriptionImg: '',
                    vendorName: 'Akshay Syal',
                    status: '',
                    description: 'Customer Not Contactable',
                    date: '12 July 2023',
                    time: '8:04 AM',
                    chipText: '',
                    chipType: '',
                },
                {
                    img1: 'ITL-logo',
                    img2: 'right-arrow',
                    img3: 'vendor-name-logo',
                    descriptionImg: 'declined-call',
                    vendorName: 'Akshay Syal',
                    status: '',
                    description: 'Called Buyer',
                    date: '12 July 2023',
                    time: '8:04 AM',
                    chipText: 'iThinkLogistics - Auto',
                    chipType: 'auto',
                    isPanel: false,
                },
                {
                    img1: 'ITL-logo',
                    img2: 'right-arrow',
                    img3: 'vendor-name-logo',
                    descriptionImg: 'declined-call',
                    vendorName: 'Akshay Syal',
                    status: {
                        text: 'Call not received by Buyer',
                        color: 'brownClr',
                    },
                    description: 'Called Buyer',
                    date: '12 July 2023',
                    time: '8:04 AM',
                    chipText: 'iThinkLogistics - Auto',
                    chipType: 'auto',
                    isPanel: false,
                },
                {
                    img1: 'ITL-logo',
                    img2: 'right-arrow',
                    img3: 'vendor-name-logo',
                    descriptionImg: '',
                    vendorName: 'Akshay Syal',
                    status: {
                        text: 'Reattempt via Ndr Call',
                        color: 'greenClr',
                    },
                    description: 'Called Buyer',
                    date: '12 July 2023',
                    time: '8:04 AM',
                    chipText: 'iThinkLogistics - Manual',
                    chipType: 'manual',
                    isPanel: false,
                },
                {
                    img1: 'ITL-logo',
                    img2: 'right-arrow',
                    img3: 'vendor-name-logo',
                    descriptionImg: '',
                    vendorName: 'Akshay Syal',
                    status: {
                        text: '',
                        color: '',
                        bgColor: '',
                    },
                    description: 'Called Buyer',
                    date: '12 July 2023',
                    time: '8:04 AM',
                    chipText: '',
                    chipType: '',
                    isPanel: true,
                    panel: {
                        heading: 'SMS',
                        img1: 'ITL-logo',
                        content: 'Order Minoxidil 5%... from Traya Health is undelievered due to residence closed; Unable to... Confirm reason: https//itl.com/order/123456789 Team, iThinkLogistics',
                    },
                },
                {
                    img1: 'you-name-logo',
                    img2: 'right-arrow',
                    img3: 'courier-logo',
                    descriptionImg: '',
                    vendorName: 'Delhivery',
                    status: {
                        text: '',
                        color: '',
                        bgColor: '',
                    },
                    description: 'Incorrect Updated Address:- B902 Delhi, India',
                    date: '12 July 2023',
                    time: '8:04 AM',
                    chipText: '',
                    chipType: '',
                    isPanel: false,
                },
            ],
        },
    ],
};
