const test = {
    is_more_data: 1,
    all_vendors_data_array: [
        {
            checked: '',
            fname: 'chetan',
            lastname: 'Parmar',
            email: 'parmar@gmail.com',
            vendor_Id: 'ITL1007',
            Phone: '9969206874',
            alternate_Phone: '9969206845',
            status: { name: 'Active', code: 'RM' },
            fssai_number: '12365478965411',
            company_name_short: 'Test iThink test1',
            website: 'www.parmar123.com',
            total_orders: '10',
            id: '9',
        },
        {
            checked: '',
            name: 'Smith',
            email: 'smith@example.com',
            vendor_Id: 'ITL1008',
            Phone: '1234567890',
            alternate_Phone: '9876543210',
            status: { name: 'Inactive', code: 'NY' },
            fssai_number: '98765432109876',
            company_name_short: 'Test Company',
            website: 'www.testcompany.com',
            total_orders: '5',
            id: '10',
        },
        {
            checked: '',
            name: 'Johnson',
            email: 'johnson@example.com',
            vendor_Id: 'ITL1009',
            Phone: '9876543210',
            alternate_Phone: '1234567890',
            status: { name: 'Blocked', code: 'LDN' },
            fssai_number: '65432109876543',
            company_name_short: 'Johnson Enterprises',
            website: 'www.johnsonent.com',
            total_orders: '15',
            id: '11',
        },
    ],
    post_search_vendor_name: '',
    status: 'success',
};

export default test;
