import createActions from './actions';
import createMutations from './mutations';
import createGetters from './getters';
const state: any = {
    dtModal: {
        // ViewDetailsModal: false,
        SelectCourierModal: false,
        VendorModal: false,
        VendorModalDatatable: false,
    },
    vendorData: [],
    DefaultColumn: [],
    editedColumnStatus: '', // For Customized Column
    dataTableSizePayload: '',
    vendorDataStatus: '',
    reverseData: '',
    allFilterData: {
        remittance_id: '',
        cn_no: '',
        invoice_id: '',
        order_id: '',
        bad_debt_no: '',
        transaction_id: '',
        claim_id: '',
        remittance_date: {
            id: '',
            value: '',
            label: '',
        },
        order_date: {
            id: '',
            value: '',
            label: '',
        },
        bad_debt_created_date: {
            id: '',
            value: '',
            label: '',
        },
        cn_date: {
            id: '',
            value: '',
            label: '',
        },
        invoice_date: {
            id: '',
            value: '',
            label: '',
        },
        cancel_request_date: {
            id: '',
            value: '',
            label: '',
        },
        wallet_transactions_date: {
            id: '',
            value: '',
            label: '',
        },
        billing_invoice_due_date: {
            id: '',
            value: '',
            label: '',
        },
        remittance_plan: {
            id: [],
            value: [],
        },
        awb_no_logistics: {
            id: [],
            value: [],
        },
        invoice_type: {
            id: [],
            value: [],
        },
        remittance_status: {
            id: [],
            value: [],
        },
        order_type: {
            id: [],
            value: [],
        },
        bad_debt_type: {
            id: [],
            value: [],
        },
        cn_status: {
            id: [],
            value: [],
        },
        order_cancel_status: {
            id: [],
            value: [],
        },
        billing_zone: {
            id: [],
            value: [],
        },
        cn_type: {
            id: [],
            value: [],
        },
        tracking_status: {
            id: [],
            value: [],
        },
        billing_invoice_status: {
            id: [],
            value: [],
        },
        claim_status: {
            id: [],
            value: [],
        },
        order_product_quantity: {
            id: [],
            value: [],
        },
        vendor_name: {
            id: [],
            value: [],
        },
        cod_generated: '',
        bill_adjusted: '',
        refund_adjusted: '',
        wallet_transfer: '',
        cod_remitted: '',
        billing_weight: '',
        total_freight_charge: '',
        wallet_debit: '',
        wallet_credit: '',
        wallet_balance: '',
        billing_invoice_amount: '',
        billing_cod_adjusted: '',
        billing_credit_note_amount: '',
        order_amount: '',
        billing_tds: '',
        billing_wallet_adjusted: '',
        billing_amount_received: '',
        billing_paid_amount: '',
        billing_round_off: '',
        billing_outstanding: '',
        cn_generated: '',
        cn_available: '',
        bad_debt_amount: '',
        cn_amount: '',
        claim_received: '',
        early_cod: '',
        advance_hold: '',
        paginatorStart: 0,
        paginatorLast: 10,
        search: '',
    },
    tempAllFilterData: '',
    // widgetTitleData: '',
    // widgetValueData: '',
    exportPayload: '',
    saveFilterResponse: '',
    savedFilteredResponse: '',
    savedDatatableResponse: '',
    exportStatus: '',
    selectedCheckbox: [],
    productDetails: [],
    openModal: {
        filterModal: false,
        viewSaveFilterModal: false,
        SaveModal: false,
        UpdateModal: false,
        saveUpdateModal: false,
    },
    viewSaveFilteredData: [],
    responseMessage: '',
    selectedTab: '',
    dtToggleData: {
        all_recharge_deduction: 'All',
        invoice_unInvoice: 'Invoice',
    },
    dtTabChangeParams: false,
};
const billing = () => ({
    namespaced: true,
    state,
    mutations: createMutations(),
    actions: createActions(),
    getters: createGetters(),
});
export default billing;
