const dummyData = [
  {
    selectedusersType: "Company",
    companyusersType: "Sole Proprietorship",
    contactPerson: "iparmar",
    companyName: "ITL",
    gstNo: "03AAACS8577K1ZZ",
    panNumber: "CVUPA4835J",
    nameOnPan: "ITHINK LOGISTICS",
    dob: "25 Feb 1998",
    aadharNumber: "124563456254545",
    nameOnAadhar: "jagdish account",
    panStatus: "Pending",
    aadharStatus: "Pending",
    panRejectRemark: "Approved",
    aadharRejectRemark: "Approved",
    rejectRemark:"Image not clear and testngd",
    rejectRemarkOne : "test img validation and testing",
    images : "[imageOne, imageTwo, imageThree]",
  },
  {
    selectedusersType: "Companys",
    companyusersType: "Sole Proprietorships",
    contactPerson: "iparmars",
    companyName: "ITLs",
    gstNo: "03AAACS8577K1ZZ",
    panNumber: "CVUPA4835J",
    nameOnPan: "ITHINK LOGISTICS",
    dob: "25 Feb 1998",
    aadharNumber: "124563456254545",
    nameOnAadhar: "jagdish accounts",
    panStatus: "Pending",
    aadharStatus: "Pending",
    panRejectRemark: "Approved",
    aadharRejectRemark: "Approved",
    rejectRemark:"Image not clear and testngd",
    rejectRemarkOne : "test img validation and testing",
    images : "[imageOne, imageTwo, imageThree]",
  }
];
export default dummyData;