import { ref } from 'vue';
import config from '@/util/config';
import { subDays } from 'date-fns';
import { FilterMatchMode } from 'primevue/api';

export const dataTableVariables = ref({
    moduleName: '',
    filterModalVisible: false,
    tempDataTableColumns: [],
    processType: '135',
    config: config,
    orderidAwbSearch: '',
    pageSize: 10,
    totalRecords: 0,
    isHeaderLoad: true,
    isSkeletonShow: true,
    activeTabIndex: 0,
    dataTableColumns: [],
    hiddenClass: 'hidden',
    orderSearch: '',
    showViewDetailsModal: false,
    position: 'right',
    selectedOption: 'Charges',
    isDropdownOpen: false,
    isDivVisible: false,
    isSaveFilterAvail: true,
    isWidgetAvail: true,
    isWidgetSekeleton: true,
    getWidgetTitle: [],
    getWidgetValues: [],
    isTabsPresent: false,
    isUniversalSearchAvail: false,
    isUniversalDateAvail: false,
    isUniversalFilterAvail: false,
    isCustomizeColumnAvail: false,
    isActionColumn: false,
    options: [
        { id: 1, label: 'Charges' },
        { id: 2, label: 'Invoice' },
    ],
    statusCheckboxData: [
        { id: 1, value: 'RTO' },
        { id: 2, value: 'Delivered' },
    ],
    statusValue: [],
    startDate: [subDays(new Date(), 29), new Date()],
    widgetSkeleton: [1, 2, 3, 4],
    defaultDatatableSize: '',
    isVendorModalVisible: false,
    savedFilterData: [],
    showEditInput: false,
    editInput: null,
    saveFilterEditId: null,
    showDeleteFilter: false,
    saveFilterOrder: [],
    savedFiltervalue: null,
    saveFilterValue: '',
    showSelectedFilter: '',
    removeCheck: false,
    filterFields: [],
    modalShow: false,
    isShowCheckbox: false,
    productDetails: '',
    scrollableTabs: [],
    selectedTabName: '',
    selectedTabHeading: '',
    activeToggleBtn: '',
    subTabName: '',
    showActionModal: false,
    isViewDetail: false,
    skeletonDataValue: false,
    rowIdValue: '',
    actionColumnWidth: '100px',
    saveFilterID: '',
    getUpdatedColumns: '',
    dataTableData: '', //    billingData
    savedDatatableResponse: [],
    exportStatus: '',
    getUpdatedSizePayload: [],
    getMappedFilterValue: '',
    saveFilterResponse: '',
    BulkVendorData: [],
    VendorId: '',
    ShowBulkVendorModal: false,
    isLoading: false,
    selectedWareHouse: '',
    getVendorValues: null,
    topHeader: JSON.parse(localStorage.getItem('top_header')),
    warehouseData: '',
    rejectInput: '',
    allFilterData: '',
    router: '',
    toast: '',
    storeFilterVariables: {},
    syncDateName: '',
    saveUpdateDTLi: false,
    changeActionColumn: false,
    changeCheckboxColumn: false,
    isExportLoading: false,
    isExportBtnAvail: true,
    apiResponse: '',
    columnsOnlyForMasters: ['vendor_name'],
    dtGlobalSearch: '',
    dtGlobalSearchId: '',
    showSkeletonInCustomizeColumn: true,
    searchFilterValidationResult: {},
    groupByColumn: [],
    isFilterSkeletonShow: false, // added for if any api change data in filter modal
});
export const apiRoutes = {
    get: '/get',
    getById: '/get/',
    edit: '/edit',
    editById: '/edit/',
    filterGet: '/get',
    filterAdd: '/add',
    filterEditById: '/edit/',
    filterDelete: '/delete/',
};

//  1 and 6 add matchMode
export const commonFilterModal = {
    //Common in all modules //
    order_id: { value: null },
    order_date: { value: null },
    vendor_name: { value: null },
    order_amount: { value: null },
    order_customer_details: { value: null },
    order_product_quantity: { value: null },
    order_type: { value: null, matchMode: FilterMatchMode.IN },
    awb_no_logistics: { value: null },
    tracking_status: { value: null },
    logistics: { value: null, matchMode: FilterMatchMode.IN },
    //Common in all modules //

    invoice_id: { value: null },
    invoice_date: { value: null },
    order_tags: { value: null },
    weight_discrepancy_status: { value: null, matchMode: FilterMatchMode.IN },
    buyer_address: { value: null },
    order_weight: { value: null },
    return_requested_date: { value: null },
    return_rejected_date: { value: null },
    order_refund_amount: { value: null },
    order_remark: { value: null },
    order_return_reason: { value: null, matchMode: FilterMatchMode.IN },
    delivery_warehouse: { value: null, matchMode: FilterMatchMode.IN },
    origin_warehouse: { value: null, matchMode: FilterMatchMode.IN },
    product_name: { value: null },
    product_sku: { value: null },
    product_category: { value: null },
    product_hsn_code: { value: null },
    product_price: { value: null },
    product_weight: { value: null },
    platform_name: { value: null },
    product_last_updated_date: { value: null },
    weight_discrepancy_date: { value: null },
    weight_dispute_date: { value: null },
    vendor_entered_weight: { value: null },
    billable_weight_in_kg: { value: null },
    itl_weight: { value: null },
    extra_weight: { value: null },
    extra_charge: { value: null },
    remittance_id: { value: null },
    remittance_date: { value: null },
    remittance_plan: { value: null, matchMode: FilterMatchMode.IN },
    cod_generated: { value: null },
    bill_adjusted: { value: null },
    refund_adjusted: { value: null },
    wallet_transfer: { value: null },
    cod_remitted: { value: null },
    early_cod: { value: null },
    advance_hold: { value: null },
    action_taken: { value: null },
    ndr_date: { value: null },
    ndr_action: { value: null },
    ndr_action_taken: { value: null },
    ndr_escalation_status: { value: null },
    ndr_status: { value: null },
    checkout_initiated_time: { value: null },
    cart_id: { value: null },
    checkout_stage: { value: null, matchMode: FilterMatchMode.IN },
    checkout_link_sent: { value: null },
    total_notification_charges: { value: null },
    total_email_charges: { value: null },
    total_sms_charges: { value: null },
    total_whatsapp_charges: { value: null },
    total_cp_charges: { value: null },
    date: { value: null },
    no_of_attempts: { value: null, matchMode: FilterMatchMode.IN },
    cn_no: { value: null },
    bad_debt_no: { value: null },
    transaction_id: { value: null },
    claim_id: { value: null },
    bad_debt_created_date: { value: null },
    billing_invoice_due_date: { value: null },
    logistics: { value: null, matchMode: FilterMatchMode.IN },
    invoice_type: { value: null, matchMode: FilterMatchMode.IN },
    bad_debt_type: { value: null, matchMode: FilterMatchMode.IN },
    cn_status: { value: null, matchMode: FilterMatchMode.IN },
    billing_zone: { value: null, matchMode: FilterMatchMode.IN },
    cn_type: { value: null, matchMode: FilterMatchMode.IN },

    claim_status: { value: null, matchMode: FilterMatchMode.IN },
    billing_weight: { value: null },
    total_freight_charge: { value: null },
    cod_adjusted: { value: null },
    billing_credit_note_amount: { value: null },
    billing_tds: { value: null },
    billing_wallet_adjusted: { value: null },
    billing_amount_received: { value: null },
    billing_paid_amount: { value: null },
    billing_round_off: { value: null },
    billing_outstanding: { value: null },
    cn_generated: { value: null },
    cn_available: { value: null },
    bad_debt_amount: { value: null },
    cliam_recived: { value: null },
    duplicate_order: { value: null },
    order_risk: { value: null, matchMode: FilterMatchMode.IN },
    pickup_cutoff: { value: null, matchMode: FilterMatchMode.IN },
    order_edd: { value: null, matchMode: FilterMatchMode.IN },
    order_fulfillment: { value: null, matchMode: FilterMatchMode.IN },
    order_buyer_intent: { value: null, matchMode: FilterMatchMode.IN },
    latest_courier_remark: { value: null, matchMode: FilterMatchMode.IN },
    order_return_delivered_date: { value: null },
    order_return_initiate_date: { value: null },
    order_delivered_date: { value: null },
    order_last_update_date: { value: null },
    order_duties: { value: null, matchMode: FilterMatchMode.IN },
    edd_date: { value: null },
    billing_invoice_status: { value: null, matchMode: FilterMatchMode.IN },
    order_cancel_status: { value: null, matchMode: FilterMatchMode.IN },
    tracking_status_intl: { value: null },
    remittance_remarks: { value: null },
    remittance_status: { value: null },
    wallet_transactions_date: { value: null },
    wallet_transactions_remark: { value: null },
    billing_invoice_amount: { value: null },
    billing_cod_adjusted: { value: null },
    cn_date: { value: null },
    cn_amount: { value: null },
    cn_utilized: { value: null },
    lost_liable_amount: { value: null },
    cancel_request_by: { value: null },
    //cancel pod request module -Domestic & INTL //
    order_cancel_request_date: { value: null },
    order_cancel_request_status: { value: null, matchMode: FilterMatchMode.IN },
    order_rto_request_date: { value: null },
    order_rto_request_status: { value: null, matchMode: FilterMatchMode.IN },
    order_pod_request_date: { value: null },
    order_pod_request_status: { value: null, matchMode: FilterMatchMode.IN },
    cancel_refund_amount: { value: null },
    order_rto_status: { value: null },
    //cancel pod request module -Domestic & INTL//

    //order management request //
    pickup_address: { value: null },
    order_last_update_date: { value: null },
    order_customer_address: { value: null },
    //order management request //

    //view user - admin //
    vendor_code: { value: null },
    user_company_name: { value: null },
    user_email: { value: null },
    user_mobile: { value: null },
    total_user_credit_amount: { value: null },
    total_user_wallet_amount: { value: null },
    user_enabled: { value: null, matchMode: FilterMatchMode.IN },
    user_created_date: { value: null },
    user_last_login_date: { value: null },
    delivery_type: { value: null, matchMode: FilterMatchMode.IN },
    user_type: { value: null, matchMode: FilterMatchMode.IN },
    user_status: { value: null, matchMode: FilterMatchMode.IN },
    //view user - admin //

    //credit-wallet - admin //
    transaction_date: { value: null },
    transaction_debit_amount: { value: null },
    transaction_credit_amount: { value: null },
    awb_no_logistics: { value: null },
    wallet_balance: { value: null },
    wallet_remarks: { value: null },
    credit_balance: { value: null },
    credit_remarks: { value: null },
    airway_bill_no: { value: null },
    //credit-wallet - admin //

    //NDR Call Details & Non Ndr Call Details- admin //
    sub_admin_name: { value: null, matchMode: FilterMatchMode.IN },
    sub_admin_email_id: { value: null },
    call_details_remark: { value: null },
    calling_date: { value: null },
    calling_reschedule_date: { value: null },
    calling_reattempt_date: { value: null },
    calling_rto_remark: { value: null },
    calling_other_remark: { value: null },
    user_company_name: { value: null },
    user_site_url: { value: null },
    calling_status: { value: null },
    order_ndr_count: { value: null },
    latest_courier_remark: { value: null },
    call_details_status: { value: null, matchMode: FilterMatchMode.IN },
    ndr_call_details_status: { value: null, matchMode: FilterMatchMode.IN },
    //NDR Call Details & Non Ndr Call Details - admin //

    //Onboard User- admin //
    sub_admin_name: { value: null, matchMode: FilterMatchMode.IN },
    user_onboard_steps: { value: null, matchMode: FilterMatchMode.IN },
    delivery_type: { value: null, matchMode: FilterMatchMode.IN },
    onboard_calling_status: { value: null, matchMode: FilterMatchMode.IN },
    onboard_calling_sub_status: { value: null, matchMode: FilterMatchMode.IN },
    onboard_user_status: { value: null, matchMode: FilterMatchMode.IN },
    oboard_lead_type: { value: null, matchMode: FilterMatchMode.IN },
    user_website: { value: null },
    user_spd: { value: null },
    calling_date: { value: null },
    next_calling_date: { value: null },
    user_wallet_amount: { value: null },
    user_signup_date: { value: null },
    user_modified_date: { value: null },
    user_utm_source: { value: null },
    onboard_user_actual_spd: { value: null },
    onboard_user_web_remark: { value: null },
    onboard_user_app_remark: { value: null },
    vendor_name_details: { value: null },
    //Onboard User- admin //

    //Update Cod amount- admin //
    cod_amount_requested_date: { value: null },
    old_order_amount: { value: null },
    revised_order_amount: { value: null },
    order_update_action_username: { value: null },
    //Update Cod amount- admin //

    //View Pincode- admin //
    pincode: { value: null },
    pincode_hub_name: { value: null },
    pincode_area: { value: null },
    pincode_state: { value: null },
    pincode_city: { value: null },
    itl_pincode_pickup_available: { value: null },
    itl_pincode_cod_available: { value: null },
    itl_pincode_prepaid_available: { value: null },
    pincode_rev_pickup_available: { value: null },
    pincode_rev_delivery_available: { value: null },
    itl_pincode_rev_pickup_available: { value: null },
    itl_pincode_rev_delivery_available: { value: null },
    pincode_pickup_available: { value: null, matchMode: FilterMatchMode.IN },
    pincode_cod_available: { value: null, matchMode: FilterMatchMode.IN },
    pincode_prepaid_available: { value: null, matchMode: FilterMatchMode.IN },
    pincode_status: { value: null, matchMode: FilterMatchMode.IN },
    //View Pincode- admin //

    //Push Pull Scan List- admin //
    push_pull_method_type: { value: null, matchMode: FilterMatchMode.IN },
    logistics: { value: null, matchMode: FilterMatchMode.IN },
    tracking_status: { value: null, matchMode: FilterMatchMode.IN },
    push_pull_status: { value: null },
    push_pull_status_type: { value: null },
    push_pull_remark: { value: null },
    push_pull_keyword: { value: null },
    //Push Pull Scan List- admin //

    //Remittance Plan- admin //
    remittance_plan_name: { value: null },
    remittance_plan_percentage: { value: null },
    remittance_plan_date: { value: null },
    //Remittance Plan- admin //

    //Staff Account- admin //
    user_name: { value: null },
    user_email: { value: null },
    user_mobile: { value: null },
    user_status: { value: null, matchMode: FilterMatchMode.IN },
    //Staff Account- admin //

    //View Pickup- admin //
    logistics_service_type: { value: null, matchMode: FilterMatchMode.IN },
    pickup_address: { value: null },
    pickup_city: { value: null },
    pickup_pincode: { value: null },
    user_address_mobile: { value: null, matchMode: FilterMatchMode.IN },
    user_mobile: { value: null },
    order_date: { value: null },
    token_number: { value: null, matchMode: FilterMatchMode.IN },
    tracking_status: { value: null, matchMode: FilterMatchMode.IN },
    //View Pickup- admin //

    //View Tickets- admin //
    ticket_close_by: { value: null, matchMode: FilterMatchMode.IN },
    dispatch_count: { value: null, matchMode: FilterMatchMode.IN },
    ticket_ageing: { value: null, matchMode: FilterMatchMode.IN },
    ticket_department: { value: null, matchMode: FilterMatchMode.IN },
    carrier_name: { value: null, matchMode: FilterMatchMode.IN },
    ticket_assign_by: { value: null, matchMode: FilterMatchMode.IN },
    ticket_assign_to: { value: null, matchMode: FilterMatchMode.IN },
    clone_ticket_date: { value: null },
    ticket_last_updated_date: { value: null },
    ticket_due_date: { value: null },
    order_edd: { value: null },
    last_attempt_date: { value: null },
    ticket_created_date: { value: null },
    ticket_closed_date: { value: null },
    pending_cs_remark: { value: null },
    clone_ticket_id: { value: null },
    ticket_lsp_remark: { value: null },
    ticket_cs_remark: { value: null },
    ticket_id: { value: null },
    ticket_subject: { value: null },
    closed_by: { value: null },
    cloned_from_ticket: { value: null },
    clone_date: { value: null },
    ticket_description: { value: null },
    ticket_category: { value: null },
    ticket_status: { value: null },
    //View Tickets- admin //

    wallet_deduction_amt: { value: null },
    wallet_refund_amt: { value: null },
    premium_amount: { value: null },
    claim_received: { value: null },
    user_email: { value: null },
    user_mobile: { value: null },
    user_created_date: { value: null },
    last_order_date: { value: null },
    user_account_type: { value: null },
    user_company_name: { value: null },

    // view order
    order_country: { value: null },
    tracking_otp_cancelled: { value: null },
    order_state: { value: null },
    order_pickup_date: { value: null },
    order_source: { value: null },
    order_state: { value: null },
    order_whatsapp_status: { value: null },
    order_incorrect_address_status: { value: null },
    order_sku: { value: null },
    is_oda: { value: null },
    order_ageing_days: { value: null },
    //Billing
    wallet_debit: { value: null },
    wallet_credit: { value: null },
    cancel_request_date: { value: null },
    //postship-nps
    nps_score: { value: null },
    nps_remarks: { value: null },

    // Connect +
    coupon_type: { value: null },
    payment_status: { value: null },
};
