export const RATECHART = {
    NAME: 'RATECHART',
    ACTIONS: {
        FETCHDEFAULTDATA: 'fetchDefaultData',
        FETCHDATA: 'fetchData',
        FETCHMODALDATA: 'fetchModalData',
        SETVENDOR: 'setVendor',
        SETBAND: 'setBand',
        SETDELIVERYTYPE: 'setDeliveryType',
        SETTABTYPE: 'setTabType',
        SETACTIVELOGISTICS: 'setActiveLogistics',
        POSTMODALDATA: 'postModalData',
        DELETERATECHART: 'deleteRateChart',
        SENDOTP: 'sendOtp',
        VERIFYOTP: 'verifyOtp',
        SETISSENDOTP: 'setIsSendOtp',
        FETCHLOGISTICSERVICETYPEBYCHANGEMODAL: 'fetchLogisticServiceTypeByChangeModal',
        SETTABLEDISABLEAPI: 'setTableDisableApi',
        FETCHBASERATECHARTMODALDROPDOWNCHANGE: 'fetchBaseRateChartModalDropdownChange',
        FETCHLOGISTICSTABTYPEDROPDOWNCHANGEMODAL: 'fetchLogisticsTabTypeDropdownChangeModal',
        SENDMAIL: 'sendMail',
        COPYVENDORCODES: 'copyVendorCodes',
        FETCHVENDORDATAFROMAPI: 'fetchVendorDataFromApi'
        // FETCHBAND: 'fetchBand'
    },
    MUTATIONS: {
        SETDEFAULTDATA: 'setDefaultData',
        SETDATA: 'setData',
        SETMODALDATA: 'setModalData',
        SETVENDOR: 'setVendor',
        SETBAND: 'setBand',
        SETDELIVERYTYPE: 'setDeliveryType',
        SETTABTYPE: 'setTabType',
        SETACTIVELOGISTICS: 'setActiveLogistics',
        SETALLLOGISTICSDATAARRAY: 'setAllLogisticsDataArray',
        SETTABLEDATA: 'setTableData',
        SETMOBILE: 'setMobile',
        SETISSENDOTP: 'setIsSendOtp',
    },
    GETTERS: {
        GETALLDATA: 'getAllData',
        GETMODALDATA: 'getModalData',
        GETVENDOR: 'getVendor',
        GETBAND: 'getBand',
        GETBANDOPTIONS: 'getBandOptions',
        GETDELIVERYTYPE: 'getDeliveryType',
        GETTABTYPE: 'getTabType',
        GETACTIVELOGISTICS: 'getActiveLogistics',
        GETALLLOGISTICSDATAARRAY: 'getAllLogisticsDataArray',
        GETLOGISTICSDATAARRAYMODAL: 'getLogisticsDataArrayModal',
        GETLOGISTICSSERVICETYPEARRAYMODAL: 'getLogisticsServiceTypeArrayModal',
        GETALLTABLEDATAARRAY: 'getAllTableDataArray',
        GETALLFLATRATETABLEDATAARRAY: 'getAllFlatRateTablesDataArray',
        GETISSENDOTP: 'getIsSendOtp',
        GETMOBILE: 'getMobile',
    },
};
